### ISSUE TITLE
运行时的插件系统如何实现？

### ISSUE THREAD

**Issue by gloryandel** [canwdev/canos-web#1]
与此项目无关。大佬，请问当项目编译启动后，Vue 如何实现安装插件进行扩展的？实现安装卸载功能

**Comment by canwdev** [comment]
动态加载js脚本或者用 eval 执行js代码都可以实现，具体要看插件系统的架构怎么设计

**Comment by Gloryandel** [comment]
> e

感谢回复和指路

**Comment by gloryandel** [comment]
> 动态加载js脚本或者用 eval 执行js代码都可以实现，具体要看插件系统的架构怎么设计

感谢回复和指路
